version: '3.8'

services:

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "8080:80" # Forwards requests from host port 8080 to container's HTTPS port 443
    volumes: #volume makes it that several containers can share a common file (called web) that is stored in the host machine or docker
      - ./web:/var/www/html #called web on my computer and this on the containers

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - ./web:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb 

