version: '3.8'

services:

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    depends_on: #controls start order but no readyness! this is a security
      - wordpress
      - mariadb
    ports:
      - "8080:443" # Forwards requests from host port 443 to container's HTTPS port 443
    volumes: #volume makes it that several containers can share a common file (called web) that is stored in the host machine or docker
      - ./wordpress:/var/www/html #called web on my computer and this on the containers
    networks:
      inception:
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - ./wordpress:/var/www/html
    env_file:
      .env
    networks:
      inception:
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      inception:
    env_file:
      .env
    restart: always

networks:
  inception:
    driver: bridge

volumes:

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/hsorel/data/mariadb1
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/hsorel/data/wordpress1
      o: bind